package me.yummydroid.app.ui

import me.yummydroid.app.YummyDroidUiState

internal fun createBrowseHomeContentModel(
    state: YummyDroidUiState,
    config: BrowseScreenRuntimeConfig,
    environment: BrowseScreenEnvironment,
    navigation: BrowseScreenNavigation,
    focusBinding: BrowseFocusBinding,
    pagerRuntime: BrowsePagerRuntime,
    visualRuntime: BrowseHomeVisualRuntime,
    catalogDialogRuntime: BrowseCatalogDialogRuntime,
    phoneSchedule: BrowsePhoneScheduleRuntime,
    scheduleSelectedEpochDay: Long,
    dpadLayerFocusRequestNonce: Long,
): BrowseHomeContentModel = BrowseHomeContentModel(
    state = state,
    browseCoordinator = config.browseCoordinator,
    effectiveSection = environment.effectiveSection,
    pagerSections = environment.pagerSections,
    pagerPage = environment.pagerPage,
    usePager = environment.usePager,
    catalogActionsEnabled = environment.catalogActionsEnabled,
    isSearching = environment.isSearching,
    isWide = environment.isWide,
    forcedOfflineMode = environment.forcedOfflineMode,
    dpadFocusEnabled = environment.dpadFocusEnabled,
    active = config.active,
    loginDialogOpen = config.loginDialogOpen,
    profileDialogOpen = config.profileDialogOpen,
    settingsDialogOpen = config.settingsDialogOpen,
    density = environment.density,
    chromePolicy = environment.chromePolicy,
    visualRuntime = visualRuntime,
    phoneScheduleDayGroups = phoneSchedule.dayGroups,
    scheduleSelectedEpochDay = scheduleSelectedEpochDay,
    showPhoneScheduleCalendar = phoneSchedule.showInBottomChrome,
    dpadLayerFocusRequestNonce = dpadLayerFocusRequestNonce,
    catalogFocusFirstRequest = navigation.focusFirstRequests.catalog,
    scheduleFocusFirstRequest = navigation.focusFirstRequests.schedule,
    historyFocusFirstRequest = navigation.focusFirstRequests.history,
    focusBinding = focusBinding,
    focusActions = navigation.focusActions,
    pagerRuntime = pagerRuntime,
    pagerBinding = navigation.pagerBinding,
    catalogDialogRuntime = catalogDialogRuntime,
)

internal fun BrowseScreenRuntimeActions.toBrowseHomeContentActions(
    onScheduleSelectedEpochDayChange: (Long) -> Unit,
): BrowseHomeContentActions = BrowseHomeContentActions(
    onQueryChange = onQueryChange,
    onSearchSubmitted = onSearchSubmitted,
    onSearchHistorySelected = onSearchHistorySelected,
    onRefresh = onRefresh,
    onLoadMoreAnime = onLoadMoreAnime,
    onFiltersChange = onFiltersChange,
    onResetFilters = onResetFilters,
    onOpenSettings = onOpenSettings,
    onOpenDownloads = onOpenDownloads,
    onClearDownloadHistory = onClearDownloadHistory,
    onCancelDownload = onCancelDownload,
    onPauseDownload = onPauseDownload,
    onResumeDownload = onResumeDownload,
    onOpenLogin = onOpenLogin,
    onOpenProfile = onOpenProfile,
    onScheduleSelectedEpochDayChange = onScheduleSelectedEpochDayChange,
    onOpenAnime = onOpenAnime,
)
